#outer_r = 5.3
outer_r_ = 6.693
inner_r = 3.0
board_size = 0.787

# need to be remeasured if charuco boards are moved
board_A2A=[1.377,4.843]
board_A2B=[13.0,14.2]
board_A2C=[12.465,9.685]

board_B2A = [14.5,13.0]
board_B2B = [4.921,1.457]
board_B2C = [9.646,12.205]

board_C2A = [13.006,14.375]
board_C2B = [12.4375,9.528]
board_C2C = [1.378,4.724]

unit = 'inch'

#recorded_center = [562,437] # manually added
#window_A= [[454,801],[667,807]]# manually added
#window_B= [[934,352], [832,169]]# manually added
#window_C= [[308,159], [195,340]]# manually added





